export function getCarList() {
  return [
    {
      vehicleId: 1,
      brand: 'Toyota',
      model: 'Camry',
      year: 2022,
      color: 'White',
      licensePlate: 'ABC 123',
      rentalPrice: 55.0,
      description: 'A reliable and fuel-efficient sedan.',
      image: 'https://example.com/toyota_camry.jpg',
      availability: true,
      fuelType: 'Gasoline',
      engineDisplacement: '2.5L',
      transmission: 'Automatic',
      bodyStructure: 'Sedan',
      seatingCapacity: 5,
      nedcFuelEfficiency: '30 MPG',
      configurations: {
        frontRadar: true,
        rearRadar: true,
        driverAssistanceSystem: true,
        tirePressureMonitoring: true,
      },
    },
    {
      vehicleId: 2,
      brand: 'Audi',
      model: 'A6',
      year: 2023,
      color: 'Black',
      licensePlate: 'XYZ 789',
      rentalPrice: 65.0,
      description: 'A luxury sedan with advanced features.',
      image: 'https://example.com/audi_a6.jpg',
      availability: true,
      fuelType: 'Gasoline',
      engineDisplacement: '3.0L',
      transmission: 'Automatic',
      bodyStructure: 'Sedan',
      seatingCapacity: 5,
      nedcFuelEfficiency: '25 MPG',
      configurations: {
        frontRadar: true,
        rearRadar: true,
        driverAssistanceSystem: true,
        tirePressureMonitoring: true,
      },
    },
    {
      vehicleId: 3,
      brand: 'Honda',
      model: 'Civic',
      year: 2022,
      color: 'Blue',
      licensePlate: 'DEF 456',
      rentalPrice: 50.0,
      description: 'An economical and compact car for city driving.',
      image: 'https://example.com/honda_civic.jpg',
      availability: true,
      fuelType: 'Gasoline',
      engineDisplacement: '1.5L',
      transmission: 'Automatic',
      bodyStructure: 'Sedan',
      seatingCapacity: 5,
      nedcFuelEfficiency: '35 MPG',
      configurations: {
        frontRadar: true,
        rearRadar: true,
        driverAssistanceSystem: false,
        tirePressureMonitoring: true,
      },
    },
    {
      vehicleId: 4,
      brand: 'BMW',
      model: 'X5',
      year: 2022,
      color: 'Silver',
      licensePlate: 'GHI 789',
      rentalPrice: 75.0,
      description: 'A luxury SUV with a powerful engine.',
      image: 'https://example.com/bmw_x5.jpg',
      availability: true,
      fuelType: 'Gasoline',
      engineDisplacement: '4.4L',
      transmission: 'Automatic',
      bodyStructure: 'SUV',
      seatingCapacity: 5,
      nedcFuelEfficiency: '20 MPG',
      configurations: {
        frontRadar: true,
        rearRadar: true,
        driverAssistanceSystem: true,
        tirePressureMonitoring: true,
      },
    },
    {
      vehicleId: 5,
      brand: 'MercedesBenz',
      model: 'EClass',
      year: 2022,
      color: 'Gray',
      licensePlate: 'JKL 101',
      rentalPrice: 70.0,
      description: 'A stylish and comfortable executive sedan.',
      image: 'https://example.com/mercedes_eclass.jpg',
      availability: true,
      fuelType: 'Gasoline',
      engineDisplacement: '2.0L',
      transmission: 'Automatic',
      bodyStructure: 'Sedan',
      seatingCapacity: 5,
      nedcFuelEfficiency: '28 MPG',
      configurations: {
        frontRadar: true,
        rearRadar: true,
        driverAssistanceSystem: true,
        tirePressureMonitoring: true,
      },
    },
  ];
}
